# .github/workflows/cd.yml

name: CD - Deploy to Production

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # 'v1.0.0'과 같은 태그가 푸시될 때

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: ci
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gongspot-ai:latest

      - name: Deploy to Server
        run: |
          ssh user@your-server-ip "docker pull ${{ secrets.DOCKER_USERNAME }}/gongspot-ai:latest && docker-compose up -d"